### ISSUE TITLE
[COMCAST] Steam downloads not hitting cache

### ISSUE THREAD

**Issue by sircod** [lancachenet/lancache-dns#31]
System:
unRAID 6.5.2

Issue Description:
Steam game downloads are not hitting the cache.

First off, all this is working fine:
- Blizzard and Origin downloads get cached and work properly.
- Running "Resolve-DnsName steamcache.cs.steampowered.com" in powershell from another computer properly returns the steamcache server IP
- I see hits on the cache for ``` "GET /serverlist/31/20/ HTTP/1.1" 200 785 "-" "Valve/Steam HTTP Client 1.0" "HIT" "valve1.steamcontent.com" "-" ```

Despite all that working fine I do not see any attempts on the cache for Steam game downloads.

Docker Container Output:

```
Running bootstrap.sh...
Enabling cache for Blizzard
Enabling cache for Frontier
Enabling cache for Origin
Enabling cache for Riot
Enabling cache for Steam
Enabling cache for Uplay
Enabling cache for Windows
Enabling custom DNS forwarder
bootstrap finished.
checking Bind9 config
Running Bind9
```

Any logs or commands I can try for more information?

**Comment by Marashni** [comment]
Check this log to see what Steam CDN servers you are actually connecting to:
**C:\Program Files (x86)\Steam\logs\content_log.txt**

You are probably connecting to a Steam CDN server that isn't in the list for the steamcache-dns container.

I had this issue where the Steam CDN load-balancer would dump me off onto a CDN hosted by Comcast. The resolution being to either forward the DNS for that CDN or blacklist it so that the Steam CDN load-balancer doesn't dump you off onto it.

This is actually discussed here: https://github.com/steamcache/steamcache-dns/issues/26

I believe the devs were looking into a redesign to handle this sort of issue.

**Comment by sircod** [comment]
Yeah, that looks like it. Mostly see references to cdn3-sea1.steamcontent.com but further down I see it is using edge.steam-dns.top.comcast.net

**Comment by astrolox** [comment]
It's my understanding that this is now fixed. PR https://github.com/uklans/cache-domains/pull/19
