### ISSUE TITLE
Steamcache-dns not correctly interpreting UKLans cache-domains file

### ISSUE THREAD

**Issue by VibroAxe** [lancachenet/lancache-dns#60]
Issue Description:
The uklans cachedomains format specifies that a domain can be included as either a specific match (eg blzddist1-a.akamaihd.net) or a wildcard match (*.blzddist1-a.akamaihd.net). Steamcache dns is interpreting both these lines as identical. In theory if only blzddist1-a.akamaihd.net is specified in the cache domains file then a dns lookup of test.blzddist1-a.akamaihd.net should return the original ip/not found.

Reproduction Steps:
* `nslookup blzddist1-a.akamaihd.net` should return lancache-ip
* `nslookup thing.blzddist1-a.akamaihd.net` should NOT return lancache-ip but it does

Docker Run Command:
n/a
Docker Container Output:
n/a

**Comment by VibroAxe** [comment]
Whilst this doesn't break anything yet this should probably be looked into as it will affect squid/monocache installs and could in theory break a future use case where we only want to cache a particular shard not an entire domain tree (may we want to cache cdn.thing.com but not manifests.cdn.thing.com)

**Comment by sta3b** [comment]
hello, i can confirm that i am having issues with battlenet only via blzddist1-a.akamaihd.net, cant update the battlenet app neither update or install any game, it gets stuck, error logs : 

2018/12/08 18:56:33 [error] 22#22: *122 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.88.252, server: , request: "GET /tpr/bnt001/patch/42/9a/429a8daceed1276a50a4bb59b4beca6e.index HTTP/1.1", upstream: "http://95.101.114.18:80/tpr/bnt001/patch/42/9a/429a8daceed1276a50a4bb59b4beca6e.index", host: "blzddist1-a.akamaihd.net"
2018/12/08 18:56:33 [error] 22#22: *122 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.88.252, server: , request: "GET /tpr/bnt001/patch/42/9a/429a8daceed1276a50a4bb59b4beca6e.index HTTP/1.1", upstream: "http://95.101.114.26:80/tpr/bnt001/patch/42/9a/429a8daceed1276a50a4bb59b4beca6e.index", host: "blzddist1-a.akamaihd.net"

that issue is only occuring with a specific ISP so i contacted them to resolve the issue with akamai

**Comment by sta3b** [comment]
i installed a second network card on the cache server and ran blizzard cache on it, worked perfectly.
so if any1 wana cache different services, run each service on a seperate network card

**Comment by VibroAxe** [comment]
This would be fixed by the switch to rpz formatted records in #69

**Comment by unspec** [comment]
#69 was merged, resolving this.
