### ISSUE TITLE
Lancache not working

### ISSUE THREAD

**Issue by SkarFire** [lancachenet/lancache-dns#91]
Issue Description:
Hey,
i´m new to docker and so i dont rly now how to find errors.
Maybe someone can help me here.
All containers start without any problems. But when i download a game, nothing happens.
No new files under /cache/data /cache, No logs in /cache/logs/access.log or error.log.
Already tryed to set the permissions on www.data, root, docker ... nothing worked.

Docker Run Command:
```
docker run --restart unless-stopped --name lancache-dns --detach -p 53:53/udp -e USE_GENERIC_CACHE=true -e LANCACHE_IP=192.168.1.10 -e UPSTREAM_DNS=192.168.2.2 lancachenet/lancache-dns:latest
docker run --restart unless-stopped --name lancache --detach -v /cache/data/cache:/data/cache -v /cache/data/logs:/data/logs -p 80:80  lancachenet/monolithic:latest
docker run --restart unless-stopped --name sniproxy  --detach -p 443:443 lancachenet/sniproxy:latest
```

Docker Container Output:

```
<!-- If there is output from the container regarding this issue, paste it here -->
```

**Comment by Atomis70** [comment]
Hello @SkarFire 

Your lancache uses the 192.168.1.10 IPv4 address and your upstream_dns uses the 192.168.2.2 IPv4 address. Have you correctly configured your DHCP server / host to use the 192.168.1.10 DNS server?

If so, it should necessarily have traffic because otherwise your host wanting to download games / browse the internet could not translate with the DNS server (which is your lancache-dns)

**Comment by Atomis70** [comment]
Can you also confirm when typing the `docker ps` command, all your machines are running correctly? With the right ports?

**Comment by SkarFire** [comment]
Hey thanks 4 the answer, 
but i totally forgot about this.
Yesterday i just wiped my hole network and did it new (better).
Today i set up the lancache and it work just fine instandly.
