### ISSUE TITLE
Unable to update new clients

### ISSUE THREAD

**Issue by SurferLancelot** [lancachenet/lancache-dns#95]
Issue Description:

When I install steam on a new computer and run the first update I get an error 

"Steam needs to be online to update.  Please confirm your network connection and try again"

When I switch DNS servers to my upsteamdns server it downloads fine and finishes updating. 

Docker Run Command:
```
docker run --name lancache-dns --detach -p 10.0.0.249:53:53/udp -e STEAMCACHE_IP=10.0.0.249 -e UPSTREAM_DNS=10.0.0.250 lancachenet/lancache-dns:latest
```

Docker Container Output:

```
This is the last entry for that machine
see the 302 error like a redirect 

[03/Sep/2019:16:34:11 +0100] "GET /client/steam_win32.zip.vz.045e3bdc708594750f8858698fa37ba56f23ee19_1207028 HTTP/1.1" 302 0 "-" "Valve/Steam HTTP Client 1.0" "MISS" "client-download.steampowered.com" "-"

```

**Comment by wofnull** [comment]
I am affected aswell from this problem first came up about 5 Months ago while trying to start a freshly installed steamgame, because steam nagged about an needed steam update which it did not get upon steam restart, until i disabled DNS Redirection to steamcache.
Problem could be that the requested source is not  located on the normal Donwload services of steam but on its own server which gets promoted via the 302 redirect. best would to be to disable the caching of client-download*.steampowered.com, as this cannot be done from docker config side

**Comment by VibroAxe** [comment]
302 isn't an error, it's just a redirect response code? I've not heard any other issues with cached updates. I suspect that you may have a corrupted file in your cache somewhere. Are there any other log entries for steam_win32.zip?
